spring :
  application :
    name : be
  #  datasource:
  #  driver-class-name: com.mysql.bc.Driver
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${MYSQL_CONNCTION}
  # Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  cache:
    type: redis
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


server:
  port: 8081
  ssl:
    enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

jwt:
  kakao:
    secret_key: ${KAKAO_JWT_KEY}
    access:
      expiration: 600000 # 100 분
    refresh:
      expiration: 86400000 # 240 시간


oauth2:
  client:
      kakao:
        client_id: ${KAKAO_CLIENT_ID} # REST API 키
        client_secret: ${KAKAO_CLIENT_SECRET} # Client Secret 키
        redirect_uri: ${KAKAO_REDIRECT_URI}
        client-name: kakao
        authorization-grant-type: authorization_code


management:
  endpoints:
    web:
      exposure:
        include: prometheus

stomp:
  endpoint: ${SPRING_SOCKET_END_POINT}